add admin Components, and adminAuth Ui
joshlw04/IrreverentIceBreaker pull request #8
Opened 2016-10-09 19:41 UTC by Naser2

This has added Admin Components, and adminAuth Ui
[tiket](https://trello.com/c/KSynrs9e/13-map-out-components-needed-for-auth-admin-ui)

2016-10-09 20:00 UTC, processprocess commented on app/app.js
> -const express = require('express');
Please bring this file back in, we need if for our back end auth

2016-10-09 20:00 UTC, processprocess commented on client/components/App.jsx
> +  sendQuestions({ body }) {
Maybe we should change this parameter to be "questions" instead of body. 
I think it will read more clearly that way

2016-10-09 20:01 UTC, processprocess commented on client/components/App.jsx
> +           .send({ body })
If we change the parameter to "questions", it should be updated here as well.

2016-10-09 20:02 UTC, processprocess commented on migrations/migrations.sql
> +  body VARCHAR NOT NULL,
If we change the parameter to "questions", it should be updated here as well.

2016-10-10 13:28 UTC, WilliamfShaw commented on client/components/App.jsx
> +  sendQuestions({ body }) {
👍

2016-10-10 14:34 UTC, Naser2 commented on client/components/App.jsx
> +  sendQuestions({ body }) {
Yes, agreed process. it makes sense. I will review this.

2016-10-10 15:06 UTC, Naser2 commented on app/app.js
> -const express = require('express');
This App folder and files are back there. Please, take a look.

2016-10-10 15:24 UTC, Naser2 commented on migrations/migrations.sql
> +  body VARCHAR NOT NULL,
I'm not sure about it. it wouldn't update. we have to alter your database manually i think.

2016-10-10 21:55 UTC, echeng924 requested changes

2016-10-10 21:55 UTC, echeng924 commented on client/components/App.jsx
> +      this.getAllAdminQuestionss();
Looks like there's an extra 's' at the end of this function **this.getAllAdminQuestionss();**

2016-10-10 21:55 UTC, echeng924 commented on client/components/admin/adminForm.jsx
> +class Admin extends React.Component {
I think class Admin should be AdminForm?

2016-10-10 21:55 UTC, echeng924 commented on client/components/admin/adminForm.jsx
> +export default Admin;
Should be updated if we update the class name to AdminForm

2016-10-10 21:55 UTC, echeng924 commented on client/components/login.jsx
> +import cookie from 'react-cookie';
Hey Nas, will this be another component?

2016-10-10 21:55 UTC, echeng924 commented on dist/index.html
>    </head>
👍  thanks for making this change!

2016-10-10 21:55 UTC, echeng924 commented on package.json
>      "superagent": "^2.3.0",
👍

2016-10-10 22:43 UTC, Naser2 commented on client/components/login.jsx
> +import cookie from 'react-cookie';
I initially wanted to make a separate component for login, but now I deleted it.

2016-10-10 22:44 UTC, Naser2 commented on client/components/App.jsx
> +      this.getAllAdminQuestionss();
Thanks for pointing this out Liz.

2016-10-10 22:45 UTC, Naser2 commented on client/components/admin/adminForm.jsx
> +export default Admin;
All the Admin has been updated to AdminForm. Thanks Liz.

2016-10-10 22:48 UTC, Naser2 commented on dist/index.html
>    </head>
It seemed as the dark blue color we originally had  was tough to stare for a long  time span, so I changed it to the lovely shade of light blue :)

2016-10-11 20:42 UTC, merged